###############################################################################
# Licensed Materials - Property of IBM.
# Copyright IBM Corporation 2017. All Rights Reserved.
# U.S. Government Users Restricted Rights - Use, duplication or disclosure 
# restricted by GSA ADP Schedule Contract with IBM Corp.
#
# Contributors:
#  IBM Corporation - initial API and implementation
###############################################################################
# license must be set to "accept" in order to accept the terms of the IBM license
license: "accept"
image:
  # repository is the container repository to use, which defaults to IIB docker registry hub image
  repository: @@@repo@@@
  # tag is the tag to use for the container repository
  tag: @@@image.tag@@@
  # pullSecret is the secret to use when pulling the image from a private registry
  pullSecret: 
  # pullPolicy of IfNotPresent causes image pulling to be skipped if it already exists. Change to Always to force a pull.
  pullPolicy: IfNotPresent
resources:
  limits:
    # cpu is specified in units of cores
    cpu: @@@iib.cores.max@@@
    # memory is specified in units of bytes
    memory: @@@iib.ram.max@@@
  requests:
    # cpu is specified in units of cores
    cpu: @@@iib.cores@@@
    # memory is specified in units of bytes
    memory: @@@iib.ram@@@
# nodename defines the name of the IIB Node which is created in the docker container
nodename: "@@@iib.nodename@@@"
# servername defines the name of the IIB Server which is created under the IIB Node
servername: "@@@iib.servername@@@"
service:  
  type: @@@iib.svc.type@@@
  webuiPort: @@@iib.httplistener.port@@@  
  serverlistenerPort: @@@iib.serverlistener.port@@@
  nodelistenerPort: @@@iib.nodelistener.port@@@
  replicas: 1
